spring:
  application:
    name: cliente-service
  config:
    import: configserver:http://localhost:8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: /clienteservice/api-docs
  swagger-ui:
    path: /clienteservice/swagger-ui.html